services:
  - type: web
    name: bot
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter @workspace/api-server run build
    startCommand: node --enable-source-maps artifacts/api-server/dist/index.mjs
    healthCheckPath: /api/healthz
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        value: 1500879202646360124
      - key: BOT_ENABLED
        value: "true"
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: MAPLE_API_KEY
        sync: false
